[workspace]
resolver = "2"
members = [
  "nixrs",
  "nixrs-derive",
  "nixrs-archive",
  "nixrs-io",
  "nixrs-legacy",
  "nixrs-ssh-store",
  "nixrs-capnp",
  "examples/nixrs-nix-store",
  "examples/nix-docker-build",
  "examples/nixrs-tvix",
]
