build-run-tests:
    cargo build --bin run-tests

[working-directory: '../nixrs-daemon-tests']
run-tests *TEST_ARGS: build-run-tests
    NIX_IMPL="../nixrs-capnp/run-tests.json" cargo test -- {{TEST_ARGS}}